# Thanks to https://github.com/joerick/cibuildwheel for windows build
# commands

language: generic

matrix:
  include:
    - os: linux
      language: python
      python: 3.6

    - os: linux
      language: python
      python: 3.7

    - os: windows
      language: shell
      before_install:
       - choco install python3 --version=3.7.6 --no-progress -y
      install:
       - C:\\Python37\\python -m pip install .
      script:
       - C:\\Python37\\python -c "import sbol2; sbol2.testSBOLHook()"

install:
  - python3 -m pip install .

script:
  - python3 -c "import sbol2; sbol2.testSBOLHook()"
  - travis_wait python3 -c "import sbol2; sbol2.testRoundTrip()"
